# Generated by Django 6.1 on 2026-08-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='receipts/')),
                ('store', models.CharField(default='Biedronka', max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'przesłano'), ('ocr_failed', 'błąd ocr'), ('parsed', 'przetworzono'), ('parse_failed', 'błąd przetwarzania'), ('reviewed', 'zweryfikowano')], default='uploaded', max_length=30)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('raw_text', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pre_discount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('had_discount', models.BooleanField(default=False)),
                ('had_deposit', models.BooleanField(default=False)),
                ('parse_warning', models.TextField(blank=True)),
                ('shared_by', models.ManyToManyField(blank=True, related_name='line_items', to='receipts.person')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='receipts.receipt')),
            ],
        ),
    ]
